[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers_postgresql.conf
    storage.path  /var/fluent-bit/storage
    storage.sync  normal
    storage.checksum off

[INPUT]
    Name              tail
    Path              /var/log/postgresql/*.log
    Parser            postgres_log          
    Tag               pgsql.log           
    Refresh_Interval  5
    Skip_Long_Lines   On
    DB                /var/fluent-bit/state.db
    Mem_Buf_Limit     10MB
    storage.type      filesystem          
    multiline.parser postgres_multiline

[FILTER]
    Name   modify
    Match  pgsql.log                    
    Add    source postgresql

[OUTPUT]
    Name                opensearch
    Match               pgsql.log       
    Host                opensearch
    Port                9200
    Index               pgsql-logs     
    HTTP_User           admin
    HTTP_Passwd         OpenSearch@2024
    TLS                 On
    TLS.Verify          Off
    Suppress_Type_Name  On
    Replace_Dots        On
    Retry_Limit         6