
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: >
        -c log_line_prefix='%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
        -c logging_collector=on
        -c log_directory=/var/log/postgresql
        -c log_filename='postgresql-%Y-%m-%d.log'
        -c log_truncate_on_rotation=off
        -c log_rotation_age=1d
        -c log_rotation_size=0
        -c log_min_messages=warning
        -c log_min_error_statement=error
        -c log_statement=none
    ports:
      - "15432:5432"
      - "2223:22"
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./postgres-logs:/var/log/postgresql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=OpenSearch@2024
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "19200:9200"
    volumes:
      - ./opensearch-data:/usr/share/opensearch/data
    networks:
      - app-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -s -k -u admin:OpenSearch@2024 https://localhost:9200/_cluster/health | grep -q 'status' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "15601:5601"
    environment:
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
    networks:
      - app-network
    depends_on:
      - opensearch


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "15050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  ansible:
    image: python:3.12-slim
    container_name: ansible
    volumes:
      - ./ansible:/ansible:rw
    working_dir: /ansible
    networks:
      - app-network
    ports:
      - "2222:22"       
    command: >
      sh -c "
        apt-get update &&
        apt-get install -y openssh-server ansible sudo &&
        mkdir -p /var/run/sshd &&
        echo 'root:root' | chpasswd &&
        sed -i 's/#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config &&
        service ssh start &&
        tail -f /dev/null"
    restart: unless-stopped
  
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_OPTS: --prefix=/
    networks:
      - app-network
    user: root
    command: |
      sh -c 'apt-get update && apt-get install -y python3 python3-venv python3-pip &&
      /usr/local/bin/jenkins.sh'

  leader:
    image: cribl/cribl:latest
    environment:
      - CRIBL_DIST_MODE=leader
      - CRIBL_DIST_LEADER_URL=tcp://${CRIBL_DIST_TOKEN:-criblmaster}@0.0.0.0:4200
      - CRIBL_VOLUME_DIR=/opt/cribl/config-volume
    ports:
      - "19000:9000"
      - "4200:4200"
    volumes:
      - "~/cribl-config:/opt/cribl/config-volume"
      - ./postgres-logs:/var/log/postgresql:ro
    networks:
      - app-network
  workers:
    image: cribl/cribl:latest
    depends_on: 
      - leader
    environment:
      - CRIBL_DIST_MODE=worker
      - CRIBL_DIST_LEADER_URL=tcp://${CRIBL_DIST_TOKEN:-criblmaster}@leader:4200
    ports:
      - "19002:9000"
    volumes:
      - ./postgres-logs:/var/log/postgresql:ro
    networks:
      - app-network
  
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - app-network

  hammerdb:
    image: tpcorg/hammerdb:latest
    container_name: hammerdb
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      DISPLAY: ":0"
    stdin_open: true 
    tty: true
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/bin/bash"]

networks:
  app-network:
    driver: bridge