[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers_postgresql.conf

[INPUT]
    Name         tail
    Path         /var/log/postgresql/*.log
    Tag          postgresql
    Refresh_Interval 5
    Skip_Long_Lines  On
    DB            /var/fluent-bit/state.db
    Mem_Buf_Limit 10MB
    storage.type  memory

[FILTER]
    Name          modify
    Match         postgresql
    Add           source postgresql

[OUTPUT]
    Name            opensearch
    Match           *
    Host            opensearch
    Port            9200
    Index           postgres-logs
    HTTP_User       admin
    HTTP_Passwd     OpenSearch@2024
    TLS             On
    TLS.verify      Off
    Suppress_Type_Name On
    Replace_Dots    On
    Logstash_Format On
    Logstash_Prefix postgres
    Logstash_DateFormat %Y.%m.%d
    Retry_Limit     6
    Buffer_Size     400MB