[PARSER]
    Name        postgres_log
    Format      regex
    Regex       ^(?<time>[^ ]+\s[^ ]+)\s\[(?<pid>[0-9]+)\]\s(?<level>[A-Z]+):\s(?<message>.*)$
    Time_Key    time
    Time_Format %Y-%m-%d %H:%M:%S %Z